Crep fix/build
SharedStake/SharedStake-ui pull request #201
Opened 2024-05-28 01:53 UTC by crepella

2024-05-28 02:29 UTC, chimera-defi requested changes

2024-05-28 02:29 UTC, chimera-defi commented on Dockerfile
> +RUN npm install @vue/cli@3.7.0 -g
npm i should install all deps.

2024-05-28 02:29 UTC, chimera-defi commented on Dockerfile
> +RUN npm -v
y tho? just debug? rm plz

2024-05-28 02:29 UTC, chimera-defi commented on babel.config.js
> +    '@babel/preset-env',
is this a no op change?

2024-05-28 02:29 UTC, chimera-defi commented on test-aliases.js
> +console.log(require.resolve('bnc-onboard'));
toss it

2024-05-28 02:29 UTC, chimera-defi commented on test-import.js
> +const Onboard = require('bnc-onboard');
toss

2024-05-28 02:29 UTC, chimera-defi commented on vue.config.js
> +                '@metamask/abi-utils': path.resolve(__dirname, 'node_modules/@metamask/abi-utils/lib/index.js')
did this get rid of the loader issues?

2024-05-28 21:01 UTC, chimera-defi commented
can we add how to run the dockerfile / how youre doing it to the readme? or as a `docker` cmd in package.json plz?

2024-05-31 11:29 UTC, crepella commented
Commands I used are 

docker build -t sharedstake-ui .
docker run -p 8080:8080 sharedstake-ui

2024-05-31 11:48 UTC, crepella commented
Added the instructions to README under 'Run with Docker'

2024-05-31 13:53 UTC, closed without merging