Re-add gauge from earlier versions to stake page
SharedStake/SharedStake-ui pull request #58
Opened 2021-03-23 10:15 UTC by exitonoff

Addresses issue https://github.com/SharedStake/SharedStake-ui/issues/52

Found the earlier gauge:
![image](https://user-images.githubusercontent.com/80589610/112125032-abb01e00-8bcb-11eb-9b53-66fbabe33542.png)

Changed some colours to make it fit to the site. Changed the calculation of ETH deposited to contract to reflect actual amount of ETH deposited (earlier it showed the shares minted / max shares). Added it to Stake-page:
![image](https://user-images.githubusercontent.com/80589610/112125125-c5516580-8bcb-11eb-9ea7-7765ff3982a0.png)

Some issues:
- it doesn't seem to work on Firefox...though it seems that there's some more problems with FF discussed at #bug-reports in Discord
  - tested with Chrome and Brave and was working fine
- didn't seem to work on mobile
  - I haven't used wallets on mobile (only Metamask on desktop), so I'm not sure how to fix this
- the gauge had previosly explanation text:
> This shows the total Eth amount that is staked to SharedStake so far.
> 320 is required (10 validators) for the first deposit to Eth2 event which locks it up. We will increase this limit to 3200, then 32000 (1000 validators) for subsequent deposit events.
>When Eth is deposited into the SharedDeposit contract, a Validator-Share-Eth2 token (vEth2) is minted. Redeemable for the deposited Eth.
- I edited it a bit to:
> Total of {{ ethDeposited }}Eth has been staked to SharedStake so far.
> 32100Eth is required (for 1000 validators) for the third deposit to ETH2 event which locks it up.
> When Eth is deposited into the SharedDeposit contract, a Validator-Share-Eth2 token (vEth2) is minted. Redeemable for the deposited Eth.
- what should it be?

2021-03-24 17:00 UTC, sharedStake-dev requested changes

2021-03-24 17:00 UTC, sharedStake-dev commented on src/components/Stake/StakeGauge.vue
> +        32100Eth is required (for 1000 validators) for the third deposit to ETH2 event
There's actually nothing more than 32 eth needed for the 3rd deposit. The tardiness has been due to figuring out more cloud providers and regions and issues with AWS. 

- Can we therefore remove the comment about the 3rd deposit? 
- Can we change `Eth` to `ETH`? 
- Can we have the base value of 32100 be dynamic? (from teh contract it's costPerValidator * numValidators)

2021-03-29 11:44 UTC, exitonoff commented
I added commit to update Earn-page's buttons' label texts, as suggested in https://github.com/SharedStake/SharedStake-ui/issues/61. Thought it would be fine to add it to this, if this PR is going to be merged anyways soon.

2021-03-29 15:18 UTC, sharedStake-dev requested changes

2021-03-29 15:18 UTC, sharedStake-dev commented on src/components/Stake/Stake.vue
> +        console.log("SASDSA")
lets get rid of the debug logs

2021-03-29 15:23 UTC, exitonoff commented on src/components/Stake/Stake.vue
> +        console.log("SASDSA")
Whoopsie, removed them. 🚯

2021-03-29 15:55 UTC, merged