Add mailing list signup to landing page
SharedStake/SharedStake-ui pull request #85
Opened 2021-04-12 18:35 UTC by exitonoff

Addresses https://github.com/SharedStake/SharedStake-ui/issues/65.

Texts and placeholder text can be changed. 
I stripped down some initial styles which were included in the html provided.

I also noticed that there's prolly typo in Mailchimp, since the url is https://**sharestake**.us1.list-manage.com as it should be share**d**stake. The return from the signup leads to nowhere (sharestake.org).

Please comment on the styles if you have any suggestions:
![image](https://user-images.githubusercontent.com/80589610/114443599-8add5600-9bd6-11eb-835c-4ec207b96624.png)
![image](https://user-images.githubusercontent.com/80589610/114443680-a2b4da00-9bd6-11eb-9d1a-b1f213c2d2cb.png)

2021-04-12 21:08 UTC, ssmangoeater commented on src/components/Common/MailingListSubscribeForm.vue
> +        action="https://sharestake.us1.list-manage.com/subscribe/post?u=6cb6b636781c4fcc0b7cbccf1&amp;id=1e3ebab5ba"
Thanks for catching that. I fixed it. Now it's "https://sharedstake.us1.list-manage.com/subscribe/post?u=6cb6b636781c4fcc0b7cbccf1&amp;id=1e3ebab5ba"

2021-04-12 21:10 UTC, ssmangoeater requested changes
Thanks for catching the typo -- you can change it to sharedstake.org now. Design looks good. Let's change the text to say "Subscribe for updates from the team"

2021-04-12 21:15 UTC, ssmangoeater requested changes
https://sharedstake.us1.list-manage.com/subscribe/post?u=6cb6b636781c4fcc0b7cbccf1&amp;id=1e3ebab5ba

2021-04-13 13:42 UTC, exitonoff commented
![image](https://user-images.githubusercontent.com/80589610/114562552-42c24000-9c77-11eb-86a5-75f92cf07c59.png)

Updated the link and title.

2021-04-13 14:47 UTC, ssmangoeater approved these changes

2021-04-13 14:48 UTC, ssmangoeater approved these changes

2021-04-13 21:48 UTC, ssmangoeater approved these changes

2021-04-13 21:48 UTC, ssmangoeater approved these changes

2021-04-14 07:21 UTC, sharedStake-main approved these changes

2021-04-14 07:21 UTC, sharedStake-main commented
Approved @exitonoff

2021-04-14 09:06 UTC, merged